default:
  is_secure: true
  credentials: [[sales,casher,admin,encoder]]
delete:
  is_secure: true
  credentials: [[encoder,admin]]
index:
  is_secure: false
view:
  is_secure: false
search:
  is_secure: false
