<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Task', 'doctrine');

/**
 * BaseTask
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $subject_class
 * @property integer $subject_id
 * 
 * @method integer getId()            Returns the current record's "id" value
 * @method string  getName()          Returns the current record's "name" value
 * @method string  getDescription()   Returns the current record's "description" value
 * @method string  getSubjectClass()  Returns the current record's "subject_class" value
 * @method integer getSubjectId()     Returns the current record's "subject_id" value
 * @method Task    setId()            Sets the current record's "id" value
 * @method Task    setName()          Sets the current record's "name" value
 * @method Task    setDescription()   Sets the current record's "description" value
 * @method Task    setSubjectClass()  Sets the current record's "subject_class" value
 * @method Task    setSubjectId()     Sets the current record's "subject_id" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTask extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('task');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('subject_class', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('subject_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}