<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AccountType', 'doctrine');

/**
 * BaseAccountType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Account
 * @property Doctrine_Collection $AccountCategory
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getName()            Returns the current record's "name" value
 * @method Doctrine_Collection getAccount()         Returns the current record's "Account" collection
 * @method Doctrine_Collection getAccountCategory() Returns the current record's "AccountCategory" collection
 * @method AccountType         setId()              Sets the current record's "id" value
 * @method AccountType         setName()            Sets the current record's "name" value
 * @method AccountType         setAccount()         Sets the current record's "Account" collection
 * @method AccountType         setAccountCategory() Sets the current record's "AccountCategory" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAccountType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('account_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Account', array(
             'local' => 'id',
             'foreign' => 'account_type_id'));

        $this->hasMany('AccountCategory', array(
             'local' => 'id',
             'foreign' => 'account_type_id'));
    }
}