<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Accountentry', 'doctrine');

/**
 * BaseAccountentry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $account_id
 * @property decimal $qty
 * @property date $date
 * @property decimal $balance
 * @property string $ref_class
 * @property integer $ref_id
 * @property integer $priority
 * @property string $type
 * @property integer $is_cancelled
 * @property string $description
 * @property timestamp $created_at
 * @property Account $Account
 * 
 * @method integer      getId()           Returns the current record's "id" value
 * @method integer      getAccountId()    Returns the current record's "account_id" value
 * @method decimal      getQty()          Returns the current record's "qty" value
 * @method date         getDate()         Returns the current record's "date" value
 * @method decimal      getBalance()      Returns the current record's "balance" value
 * @method string       getRefClass()     Returns the current record's "ref_class" value
 * @method integer      getRefId()        Returns the current record's "ref_id" value
 * @method integer      getPriority()     Returns the current record's "priority" value
 * @method string       getType()         Returns the current record's "type" value
 * @method integer      getIsCancelled()  Returns the current record's "is_cancelled" value
 * @method string       getDescription()  Returns the current record's "description" value
 * @method timestamp    getCreatedAt()    Returns the current record's "created_at" value
 * @method Account      getAccount()      Returns the current record's "Account" value
 * @method Accountentry setId()           Sets the current record's "id" value
 * @method Accountentry setAccountId()    Sets the current record's "account_id" value
 * @method Accountentry setQty()          Sets the current record's "qty" value
 * @method Accountentry setDate()         Sets the current record's "date" value
 * @method Accountentry setBalance()      Sets the current record's "balance" value
 * @method Accountentry setRefClass()     Sets the current record's "ref_class" value
 * @method Accountentry setRefId()        Sets the current record's "ref_id" value
 * @method Accountentry setPriority()     Sets the current record's "priority" value
 * @method Accountentry setType()         Sets the current record's "type" value
 * @method Accountentry setIsCancelled()  Sets the current record's "is_cancelled" value
 * @method Accountentry setDescription()  Sets the current record's "description" value
 * @method Accountentry setCreatedAt()    Sets the current record's "created_at" value
 * @method Accountentry setAccount()      Sets the current record's "Account" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAccountentry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('accountentry');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('account_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('qty', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 18,
             'scale' => '2',
             ));
        $this->hasColumn('date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('balance', 'decimal', 10, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             'scale' => '2',
             ));
        $this->hasColumn('ref_class', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('ref_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('priority', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('type', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('is_cancelled', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('description', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Account', array(
             'local' => 'account_id',
             'foreign' => 'id'));
    }
}