<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Links', 'doctrine');

/**
 * BaseLinks
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $type
 * @property string $url
 * 
 * @method integer getId()   Returns the current record's "id" value
 * @method string  getType() Returns the current record's "type" value
 * @method string  getUrl()  Returns the current record's "url" value
 * @method Links   setId()   Sets the current record's "id" value
 * @method Links   setType() Sets the current record's "type" value
 * @method Links   setUrl()  Sets the current record's "url" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLinks extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('links');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('type', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('url', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}