<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Employee', 'doctrine');

/**
 * BaseEmployee
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $commission
 * @property integer $is_technician
 * @property Doctrine_Collection $Invoice
 * @property Doctrine_Collection $Purchase
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getName()          Returns the current record's "name" value
 * @method integer             getCommission()    Returns the current record's "commission" value
 * @method integer             getIsTechnician()  Returns the current record's "is_technician" value
 * @method Doctrine_Collection getInvoice()       Returns the current record's "Invoice" collection
 * @method Doctrine_Collection getPurchase()      Returns the current record's "Purchase" collection
 * @method Employee            setId()            Sets the current record's "id" value
 * @method Employee            setName()          Sets the current record's "name" value
 * @method Employee            setCommission()    Sets the current record's "commission" value
 * @method Employee            setIsTechnician()  Sets the current record's "is_technician" value
 * @method Employee            setInvoice()       Sets the current record's "Invoice" collection
 * @method Employee            setPurchase()      Sets the current record's "Purchase" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmployee extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('employee');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('username', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('commission', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('is_technician', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Invoice', array(
             'local' => 'id',
             'foreign' => 'salesman_id'));

        $this->hasMany('Purchase', array(
             'local' => 'id',
             'foreign' => 'employee_id'));
    }
}