<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PurchaseTemplate', 'doctrine');

/**
 * BasePurchaseTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Purchase
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getName()     Returns the current record's "name" value
 * @method Doctrine_Collection getPurchase() Returns the current record's "Purchase" collection
 * @method PurchaseTemplate    setId()       Sets the current record's "id" value
 * @method PurchaseTemplate    setName()     Sets the current record's "name" value
 * @method PurchaseTemplate    setPurchase() Sets the current record's "Purchase" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePurchaseTemplate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('purchase_template');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Purchase', array(
             'local' => 'id',
             'foreign' => 'template_id'));
    }
}