<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Outcheck', 'doctrine');

/**
 * BaseOutcheck
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $checkno
 * @property date $date
 * @property date $datereceived
 * @property enum $status
 * @property decimal $amount
 * @property integer $supplier_id
 * 
 * @method integer  getId()           Returns the current record's "id" value
 * @method string   getCheckno()      Returns the current record's "checkno" value
 * @method date     getDate()         Returns the current record's "date" value
 * @method date     getDatereceived() Returns the current record's "datereceived" value
 * @method enum     getStatus()       Returns the current record's "status" value
 * @method decimal  getAmount()       Returns the current record's "amount" value
 * @method integer  getSupplierId()   Returns the current record's "supplier_id" value
 * @method Outcheck setId()           Sets the current record's "id" value
 * @method Outcheck setCheckno()      Sets the current record's "checkno" value
 * @method Outcheck setDate()         Sets the current record's "date" value
 * @method Outcheck setDatereceived() Sets the current record's "datereceived" value
 * @method Outcheck setStatus()       Sets the current record's "status" value
 * @method Outcheck setAmount()       Sets the current record's "amount" value
 * @method Outcheck setSupplierId()   Sets the current record's "supplier_id" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOutcheck extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('outcheck');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('checkno', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('datereceived', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('status', 'enum', 7, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'Pending',
              1 => 'Cleared',
              2 => 'Bounced',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 7,
             ));
        $this->hasColumn('amount', 'decimal', 10, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             'scale' => '2',
             ));
        $this->hasColumn('supplier_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}