<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Subsidiary', 'doctrine');

/**
 * BaseSubsidiary
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $code
 * @property string $name
 * @property string $account_code
 * @property integer $fund_id
 * 
 * @method integer    getId()           Returns the current record's "id" value
 * @method string     getCode()         Returns the current record's "code" value
 * @method string     getName()         Returns the current record's "name" value
 * @method string     getAccountCode()  Returns the current record's "account_code" value
 * @method integer    getFundId()       Returns the current record's "fund_id" value
 * @method Subsidiary setId()           Sets the current record's "id" value
 * @method Subsidiary setCode()         Sets the current record's "code" value
 * @method Subsidiary setName()         Sets the current record's "name" value
 * @method Subsidiary setAccountCode()  Sets the current record's "account_code" value
 * @method Subsidiary setFundId()       Sets the current record's "fund_id" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubsidiary extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('subsidiary');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('code', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('name', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('account_code', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('fund_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}