<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Incheck', 'doctrine');

/**
 * BaseIncheck
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $checkno
 * @property date $date
 * @property date $datereceived
 * @property enum $status
 * @property decimal $amount
 * @property integer $customer_id
 * 
 * @method integer getId()           Returns the current record's "id" value
 * @method string  getCheckno()      Returns the current record's "checkno" value
 * @method date    getDate()         Returns the current record's "date" value
 * @method date    getDatereceived() Returns the current record's "datereceived" value
 * @method enum    getStatus()       Returns the current record's "status" value
 * @method decimal getAmount()       Returns the current record's "amount" value
 * @method integer getCustomerId()   Returns the current record's "customer_id" value
 * @method Incheck setId()           Sets the current record's "id" value
 * @method Incheck setCheckno()      Sets the current record's "checkno" value
 * @method Incheck setDate()         Sets the current record's "date" value
 * @method Incheck setDatereceived() Sets the current record's "datereceived" value
 * @method Incheck setStatus()       Sets the current record's "status" value
 * @method Incheck setAmount()       Sets the current record's "amount" value
 * @method Incheck setCustomerId()   Sets the current record's "customer_id" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIncheck extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('incheck');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('checkno', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('datereceived', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('status', 'enum', 7, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'Pending',
              1 => 'Cleared',
              2 => 'Bounced',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 7,
             ));
        $this->hasColumn('amount', 'decimal', 10, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             'scale' => '2',
             ));
        $this->hasColumn('customer_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}