<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Countries', 'doctrine');

/**
 * BaseCountries
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $country_id
 * @property string $country
 * 
 * @method integer   getCountryId()  Returns the current record's "country_id" value
 * @method string    getCountry()    Returns the current record's "country" value
 * @method Countries setCountryId()  Sets the current record's "country_id" value
 * @method Countries setCountry()    Sets the current record's "country" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCountries extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('countries');
        $this->hasColumn('country_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('country', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}