<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Pettycash', 'doctrine');

/**
 * BasePettycash
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $pettycashno
 * @property date $date
 * @property decimal $amount
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method string    getPettycashno() Returns the current record's "pettycashno" value
 * @method date      getDate()        Returns the current record's "date" value
 * @method decimal   getAmount()      Returns the current record's "amount" value
 * @method Pettycash setId()          Sets the current record's "id" value
 * @method Pettycash setPettycashno() Sets the current record's "pettycashno" value
 * @method Pettycash setDate()        Sets the current record's "date" value
 * @method Pettycash setAmount()      Sets the current record's "amount" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePettycash extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pettycash');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('pettycashno', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('amount', 'decimal', 10, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             'scale' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}