generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Purchasedetail
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          purchasedetail
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    
        display: [_purchase_id, product_id, description, sellprice, qty, price, discrate, discamt, total]
      edit:    ~
      new:     ~
