<?php

/**
 * Customer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Customer extends BaseCustomer
{
  function getInvoices($order="asc")
  {
      return Doctrine_Query::create()
        ->from('Invoice i')
        ->where('i.customer_id = '.$this->getId())
        ->orderBy("date ".$order)
        ->execute();
    
  }

}
