<?php

/**
 * Invoice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Invoice extends BaseInvoice
{
  public $accountentriesarray=null;
  public $accountids=null;
  public $accounts=null;
  public $events=null;
  function __toString(){return $this->getInvoiceTemplate()." ".$this->getInvno();}
  function getName(){return $this->getInvno();}
  function isCancelled(){return $this->getStatus()=="Cancelled";}
  function cascadeCancel()
  {
  	foreach($this->getEvents() as $event)
  		$event->cascadeCancel();
  
  	foreach($this->getInvoicedetail() as $detail)
  		$detail->cascadeCancel();

  	$this->setStatus("Cancelled");
  	$this->save();
  }
/*
  function calc()
  {
    $details=$this->getInvoicedetail();
    $total=0;
    $description=null;
    foreach($details as $detail)
    {
      $total+=$detail->getTotal();
    }
    $this->setTotal($total-$this->getDiscamt());

    //if($this->getCash()+$this->getChequeamt()+$this->getCredit()!=$this->getTotal())
    {
      switch($this->getSaletype())
      {
        case "Cash":
          $this->setCash($this->getTotal());
          $this->setChequeamt(0);
          $this->setCredit(0);
          $description="Cash Sale";
          break;
        case "Cheque":
          $this->setCash(0);
          $this->setChequeamt($this->getTotal());
          $this->setCredit(0);
          $description="Check Sale";
          break;
        case "Account":
          $this->setCash(0);
          $this->setChequeamt(0);
          $this->setCredit($this->getTotal());
          $description="Credit Sale";
          break;
        default:
          $description="Mixed Sale";
          $this->setCash($this->getTotal()-$this->getChequeamt()-$this->getCredit());
      }
      $this->setSalesAccountEntry($this->getTotal(),$description);

      //if it exists, and >0, update
      //if it doesn't exist, and >0, create
      //if it exists, and 0, delete
      //if it doesn't exist, and 0, do nothing
      if($this->getCash()!=0)
        $this->setCashOnHandAccountEntry($this->getCash(),$description);
      else if($this->getCashOnHandAccountEntry())
        $this->getCashOnHandAccountEntry()->delete();

      if($this->getCredit()!=0)
        $this->setReceivablesAccountEntry($this->getCredit(),$description);
      else if($this->getReceivablesAccountEntry())
        $this->getReceivablesAccountEntry()->delete();

      if($this->getChequeamt()!=0)
        $this->setInChecksAccountEntry($this->getChequeamt(),$description);
      else if($this->getInChecksAccountEntry())
        $this->getInChecksAccountEntry()->delete();

    }
    {
      //adjust balance according to payables acctentries
      $balance=$this->getReceivablesTotal();

      $this->setBalance($balance);
      if($this->getStatus()=="Cancelled");
      else if($this->getTotal()>0 and $balance==0)
        $this->setStatus("Paid");
      else
        $this->setStatus("Pending");
    }

  }
*/
  function calc()
  {
    $details=$this->getInvoicedetail();
    $total=0;
    $totaldiscamt=0;
    $description=null;
    foreach($details as $detail)
    {
      $total+=$detail->getTotal();
      $totaldiscamt+=$detail->getDiscamt();
    }
    $this->setTotal($total);
    $this->setDiscamt($totaldiscamt);

    //if($this->getCash()+$this->getChequeamt()+$this->getCredit()!=$this->getTotal())
    {
      switch($this->getSaletype())
      {
        case "Cash":
          $this->setCash($this->getTotal());
          $this->setChequeamt(0);
          $this->setCredit(0);
          $description="Cash Sale";
          break;
        case "Cheque":
          $this->setCash(0);
          $this->setChequeamt($this->getTotal());
          $this->setCredit(0);
          $description="Check Sale";
          break;
        case "Account":
          $this->setCash(0);
          $this->setChequeamt(0);
          $this->setCredit($this->getTotal());
          $description="Credit Sale";
          break;
        default:
          $description="Mixed Sale";
          $this->setCash($this->getTotal()-$this->getChequeamt()-$this->getCredit());
      }
      //accounting----------------------------
//      $this->setSalesAccountEntry($this->getTotal(),$description);

      //if it exists, and >0, update
      //if it doesn't exist, and >0, create
      //if it exists, and 0, delete
      //if it doesn't exist, and 0, do nothing
//      if($this->getCash()!=0)
//        $this->setCashOnHandAccountEntry($this->getCash(),$description);
//      else if($this->getCashOnHandAccountEntry())
//        $this->getCashOnHandAccountEntry()->delete();
//
//      if($this->getCredit()!=0)
//        $this->setReceivablesAccountEntry($this->getCredit(),$description);
//      else if($this->getReceivablesAccountEntry())
//        $this->getReceivablesAccountEntry()->delete();
//
//      if($this->getChequeamt()!=0)
//        $this->setInChecksAccountEntry($this->getChequeamt(),$description);
//      else if($this->getInChecksAccountEntry())
//        $this->getInChecksAccountEntry()->delete();
      //end accounting----------------------------

    }
    {
      //adjust balance according to payables acctentries
      //$balance=$this->getReceivablesTotal();
      
      $totalpaid=0;
      $totalpaid+=$this->getCash();
      $totalpaid+=$this->getChequeamt();
      
      $events=$this->getEvents();
      foreach($events as $event)
      {
        $totalpaid+=$event->getAmount();
      }
      
      $balance=$this->getTotal()-$totalpaid;

      $this->setBalance($balance);
      if($this->getStatus()=="Cancelled");
      else if($this->getTotal()>0 and $balance==0)
        $this->setStatus("Paid");
      else
        $this->setStatus("Pending");
    }

  }

  public function getAccountentries($includeevents=false)
  {
      $query= Doctrine_Query::create()
        ->from('Accountentry ae, ae.Account a')
        ->orderBy('created_at, id')
        ->where('ae.ref_id = '.$this->getId())
      	->andWhere('ae.ref_class = "Invoice"')
      	->andWhere('ae.account_id = '.$this->accountids['account_id_receivables'])
        ;

      if($includeevents)
      {
        $events=$this->getEvents();
        $event_ids=array();
        foreach($events as $event)$event_ids[]=$event->getId();

        //only if events exist
        if(count($event_ids)>0)
          $query
          	->orWhere('ae.ref_class = "Event"')
            ->andWhereIn('ae.ref_id',$event_ids)
          	->andWhere('ae.account_id = '.$this->accountids['account_id_receivables'])
            ;
      }
        
      return $query->execute();
  }
    /*
      3 	account_id_cash_on_hand 	3
      4 	account_id_petty_cash 	9
      5 	account_id_payables 	12
      14 	account_id_cash_at_home 	6
      15 	account_id_utilitiesexpense 	7
      16 	account_id_merchandiseexpense 	8
      17 	account_id_salesincome 	10
      18 	account_id_receivables 	11    
      account_id_inchecks
    */
  public function getReceivablesTotal()
  {
    $entries=$this->getReceivablesAccountentries();
    $balance=0;
    foreach($entries as $entry)
      $balance+=$entry->getQty();
    return $balance;
  }
  public function getReceivablesAccountentries()
  {
      $this->getAccountIds();
      $query= Doctrine_Query::create()
        ->from('Accountentry ae, ae.Account a')
        ->orderBy('created_at, id')
        ->where('ae.ref_id = '.$this->getId())
      	->andWhere('ae.ref_class = "Invoice"')
      	->andWhere('ae.account_id = '.$this->accountids["account_id_receivables"])
        ;

      {
        $events=$this->getEvents();
        $event_ids=array();
        foreach($events as $event)$event_ids[]=$event->getId();

        //only if events exist
        if(count($event_ids)>0)
          $query
          	->orWhere('ae.ref_class = "Event"')
            ->andWhereIn('ae.ref_id',$event_ids)
          	->andWhere('ae.account_id = '.$this->accountids["account_id_receivables"])
            ;
      }
        
      return $query->execute();
  }
  public function getAccountIds($force=false)
  {
    if($this->accountids==null or $force)
      $this->accountids=SettingsTable::fetchAll();
    return $this->accountids;
  }
  public function getAccountEntry($settingname,$create=false,$qty=0,$description=null)
  {
    $this->getAccountentriesArray();
    $this->getAccountIds();
    $account_id=$this->accountids[$settingname];
    $entry=$this->accountentriesarray[$account_id];

    //if it does not exist, and "create or update"
    if(!$entry and $create)
    {
      $account=AccountTable::fetchById($account_id);
      $entry=$account->addEntry($this->getDate(),$qty,"Invoice",$this->getId(),null,$description);
    }
    //if it does exist, and "create or update"
    else if($create)
    {
      $entry->setQty($qty);
      $entry->setBalance(null);
      if($description)
        $entry->setDescription($description);
      $entry->save();
      $entry->getAccount()->calcFromAccountentry($entry);
    }
    return $entry;
  }
  public function getCashOnHandAccountEntry()  {return $this->getAccountEntry('account_id_cash_on_hand');}
  public function getPettyCashAccountEntry()  {return $this->getAccountEntry('account_id_petty_cash');}
  public function getPayablesAccountEntry()  {return $this->getAccountEntry('account_id_payables');}
  public function getCashAtHomeAccountEntry()  {return $this->getAccountEntry('account_id_cash_at_home');}
  public function getUtilitiesExpenseAccountEntry()  {return $this->getAccountEntry('account_id_utilitiesexpense');}
  public function getMerchandiseExpenseAccountEntry()  {return $this->getAccountEntry('account_id_merchandiseexpense');}
  public function getSalesAccountEntry()  {return $this->getAccountEntry('account_id_salesincome');}
  public function getReceivablesAccountEntry()  {return $this->getAccountEntry('account_id_receivables');}
  public function getInChecksAccountEntry()  {return $this->getAccountEntry('account_id_inchecks');}


  public function setAccountEntry($settingname,$qty,$description)
  {
    //fetch account entry
    return $this->getAccountEntry($settingname,true,$qty,$description);
  }
  public function setCashOnHandAccountEntry($qty,$description)  {return $this->setAccountEntry('account_id_cash_on_hand',$qty,$description);}
  public function setPettyCashAccountEntry($qty,$description)  {return $this->setAccountEntry('account_id_petty_cash',$qty,$description);}
  public function setPayablesAccountEntry($qty,$description)  {return $this->setAccountEntry('account_id_payables',$qty,$description);}
  public function setCashAtHomeAccountEntry($qty,$description)  {return $this->setAccountEntry('account_id_cash_at_home',$qty,$description);}
  public function setUtilitiesExpenseAccountEntry($qty,$description)  {return $this->setAccountEntry('account_id_utilitiesexpense',$qty,$description);}
  public function setMerchandiseExpenseAccountEntry($qty,$description)  {return $this->setAccountEntry('account_id_merchandiseexpense',$qty,$description);}
  public function setSalesAccountEntry($qty,$description)  {return $this->setAccountEntry('account_id_salesincome',$qty,$description);}
  public function setReceivablesAccountEntry($qty,$description)  {return $this->setAccountEntry('account_id_receivables',$qty,$description);}
  public function setInChecksAccountEntry($qty,$description)  {return $this->setAccountEntry('account_id_inchecks',$qty,$description);}

  public function getAccountentriesArray($force=false)
  {
    //if data is already loaded, just return it
    if($this->accountentriesarray!=null and !$force)
    {
      return $this->accountentriesarray;
    }
    
    $accountentries= Doctrine_Query::create()
      ->from('Accountentry a')
      ->where('a.ref_id = '.$this->getId())
    	->andWhere('a.ref_class = "Invoice"')
      ->orderBy('date, priority')
      ->execute();

    foreach($accountentries as $entry)
    {
      $this->accountentriesarray[$entry->getAccountId()]=$entry;
    }

    return $this->accountentriesarray;
  }
  function getParticularsString()
  {
    $array=array();
    foreach($this->getInvoicedetail() as $detail)
    {
      $string=$detail->getProduct()->getName();
      if($detail->getQty()<0)$string.=" (return)";

      $array[]=$string;
    }
    return implode(", ",$array);
  }
  function genCustomer()
  {
    if($this->getCustomerName() and $this->getCustomer()->getName()=="-")
    {

      //see if customer exists      
      $customer = Doctrine_Query::create()
        ->from('Customer c')
        ->where('c.name = "'.$this->getCustomerName().'"')
        ->fetchOne();

      //if not, create
      if(!$customer)
      {
        $customer=new Customer();
        $customer->setName($this->getCustomerName());
        $customer->setPhone1($this->getCustomerPhone());
        $customer->save();
      }
      else if($customer->getPhone1()==null or $customer->getPhone1()=="")
      {
        $customer->setPhone1($this->getCustomerPhone());
        $customer->save();
      }

      //set as customer, empty customername
      $this->setCustomerId($customer->getId());
      $this->setCustomerName("");
      $this->setCustomerPhone("");
      $this->save();

    }
    
    
  }
  function getEvents()
  {
    return Doctrine_Query::create()
      ->from('Event e')
      ->where('e.parent_class = "Invoice"')
      ->andWhere('e.parent_id = '.$this->getId())

      ->execute();
  }
  function getInvoicedetails()
  {
      return Doctrine_Query::create()
        ->from('Invoicedetail i, i.Product p')
        ->where('i.invoice_id = '.$this->getId())
        ->execute();
    
  }
  function getCommission($employee)
  {
/*
product.isservice values: 
0 = commission to salesman, 
1 = commission to technician, 
2: commission to both (panel, but technician commission 3%), 
3: commission to none
*/
    $commission=0;
    $commissionrate=$employee->getCommission()/1000;

    //if employee is technician
    if($employee->getIsTechnician()==1)
    {
      //foreach item
      foreach($this->getInvoicedetail() as $detail)
      {
        //if item is service (is_service=1), add to commission
        $isservice=$detail->getProduct()->getIsService();
        if($isservice==1 or $isservice==2)$commission+=$detail->getTotal();
      }
    }
    //else if employee is salesman
    elseif($employee->getIsTechnician()==0)
    {
      //foreach item
      foreach($this->getInvoicedetail() as $detail)
      {
        //if item is not service (is_service=0), add to commission
        $isservice=$detail->getProduct()->getIsService();
        if($isservice==0 or $isservice==2)$commission+=$detail->getTotal();
     }
    }
    //return total commissionable amount * employee commission rate * decimal multiplier
    return $commission;
  }
  function getCommissionTotal($employee)
  {
    $commission=0;
    $commissionrate=$employee->getCommission()/1000;

    //if employee is technician
    if($employee->getIsTechnician()==1)
    {
      //foreach item
      foreach($this->getInvoicedetail() as $detail)
      {
        //if item is service (is_service=1), add to commission
        $isservice=$detail->getProduct()->getIsService();
         if($isservice==1)$commission+=$detail->getTotal()*$commissionrate;
         else if($isservice==2)$commission+=$detail->getTotal()*0.03; //fixed commission rate for control panels
      }
    }
    //else if employee is salesman
    elseif($employee->getIsTechnician()==0)
    {
      //foreach item
      foreach($this->getInvoicedetail() as $detail)
      {
        //if item is not service (is_service=0), add to commission
        $isservice=$detail->getProduct()->getIsService();
        if($isservice==0 or $isservice==2)$commission+=$detail->getTotal()*$commissionrate;
     }
    }
    return $commission;
  }
  function getUpdateChequedata()
  {
	  $cheques=$this->getChequepayments();
	  $chequedata=array();
	  if($this->getCheque())
	    $chequedata[]=$this->getCheque()." (P".$this->getChequeamt()." ".$this->getChequedate().")";
	  
	  foreach($cheques as $cheque)
	  {
		  $chequedata[]=$cheque->getDetail1()." (P".$cheque->getAmount()." ".$cheque->getDetail2().") ";
	  }
    $this->setChequedata(implode(", ",$chequedata));
  }
  function getChequepayments()
  {
	  $cheques=Doctrine_Query::create()
          ->from('Event e')
          ->orderBy('date')
          ->where('e.type = "ChequeCollect"')
        	->andWhere('e.parent_class = "Invoice"')
        	->andWhere('e.parent_id = '.$this->getId())
        	->execute()
          ;
	  return $cheques;
  }
  function getIsTemporaryString()
  {
  	switch($this->getIsTemporary())
  	{
  		case 0: return "Closed";
  		case 1: return "Checked Out";
  		case 2: return "New";
  	}
  }
}
