<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Journal extends BaseJournal
{
  function __toString(){return $this->getName();}
  function getJournalEntryQuery($startdate=null,$enddate=null)
  {
    $query= Doctrine_Query::create()
      ->from('JournalEntry je, je.AccountEntries ae')
      ->where('je.journal_id = ?',$this->getId())
      //->orderBy('je.id')
      ;	    if($startdate)
      $query->andWhere('je.date >= "'.$startdate.'"');
    if($enddate)
      $query->andWhere('je.date <= "'.$enddate.'"');
   return $query;
  }
  function cascadeDelete()
  {
    foreach($this->getJournalEntries() as $jentry)
      $jentry->cascadeDelete();
    $this->delete();
  }
  function toTable()
  {
    $content="";
    $content.="Date"."\t";
    $content.="JEV No."."\t";
    $content.="Resp Center"."\t";
    $content.="Ref"."\t";
    $content.="Particulars"."\t";
    $content.="Payee"."\t";
    $content.="Check No."."\t";
    $content.="PTO"."\t";
    $content.="DV No."."\t";
    $content.="Ob.R. No."."\t";
    $content.="Account Code"."\t";
    $content.="Account Name"."\t";
    $content.="Debit"."\t";
    $content.="Credit"."\t";
    
    $content=str_replace("\t","</td><td>",$content);
    $content="<tr><td>".$content."</td></tr>";
    
    foreach($this->getJournalEntries() as $jentry)
      $content.=$jentry->toTable();
    
    $header=
      "<tr><td>".$this->getName()."</td></tr>"
      ."<tr><td>Quirino Province</td></tr>"
      ."<tr><td>Month: ".$this->getPeriod()->getName()."</td></tr>"
      ."<tr><td>".$this->getFund()->getName()."</td></tr>";
    
    $content="<table>".$header.$content."</table>";
    
    return $content;
  }
}
