generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Invoicedetail
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          invoicedetail
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    
        display: [_invoice_id, product_id, description, price, qty, discrate, discamt, total]
      edit:    ~
      new:     ~
